name: broadband
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.10
  - numpy=1.19.2
  - matplotlib=3.3.4
  - netcdf4=1.5.7
  - libnetcdf=4.6.1
  - scipy=1.6.1
  - pandas=1.2.4
  - xarray=0.17.0
  - dask=2021.6.0
  - cmocean=2.0
  - cartopy=0.18.0
  - xrft=0.3.0
  - jupyterlab=3.0.14
